/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package shanghuang.financialmanagement;
import javax.swing.*;

/**
 *
 * @author shanghuang
 */
public class AuthenticationFrame extends javax.swing.JFrame {
    
    public String getPassCodeInputFieldText() {
        return PasscodeInputField.getText();
    }

    /**
     * Creates new form AuthenticationFrame
     */
    public AuthenticationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AuthenticatonFrameLabel = new javax.swing.JLabel();
        PasscodeInputField = new javax.swing.JTextField();
        AuthenticationFrameConfirmButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Theo dõi chi tiêu cá nhân");
        setLocation(new java.awt.Point(950, 540));
        setResizable(false);

        AuthenticatonFrameLabel.setFont(new java.awt.Font("SF Mono SemiBold", 0, 36)); // NOI18N
        AuthenticatonFrameLabel.setText("Nhập mã bảo mật");

        PasscodeInputField.setFont(new java.awt.Font("SF Mono SemiBold", 0, 36)); // NOI18N

        AuthenticationFrameConfirmButon.setFont(new java.awt.Font("SF Mono SemiBold", 0, 24)); // NOI18N
        AuthenticationFrameConfirmButon.setText("OK");
        AuthenticationFrameConfirmButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AuthenticationFrameConfirmButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(359, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(AuthenticatonFrameLabel)
                    .addComponent(PasscodeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AuthenticationFrameConfirmButon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(335, 335, 335))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(AuthenticatonFrameLabel)
                .addGap(32, 32, 32)
                .addComponent(PasscodeInputField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(AuthenticationFrameConfirmButon)
                .addContainerGap(245, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AuthenticationFrameConfirmButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AuthenticationFrameConfirmButonActionPerformed
        // TODO add your handling code here:
        String InputText = PasscodeInputField.getText();
        if (!InputText.isEmpty()) {
            if (InputText.contains("181105")) {
                this.dispose();
                MainFunctionFrame mainframe = new MainFunctionFrame();
                mainframe.setVisible(true); 
            } else {
                JOptionPane.showMessageDialog(null, "Wrong passcode, input again");
                PasscodeInputField.setText("");
            }
        }
    }//GEN-LAST:event_AuthenticationFrameConfirmButonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            String osName = System.getProperty("os.name").toLowerCase();
    
            if (osName.contains("linux")) {
                // Sử dụng GTK trên Linux
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("GTK+".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } else if (osName.contains("windows")) {
                // Sử dụng giao diện Windows trên Windows
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Windows".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuthenticationFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AuthenticationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AuthenticationFrameConfirmButon;
    private javax.swing.JLabel AuthenticatonFrameLabel;
    private javax.swing.JTextField PasscodeInputField;
    // End of variables declaration//GEN-END:variables
    
}
